### PR TITLE
loadbalance: set nodecount to 2 when create lb

### PR DESCRIPTION
**Pull request by duanjiong**
Notice: We don't change the number of nodes of an existing load balancer, you can change it in the portal if you want.

and fixed some formatting issues

Signed-off-by: Duan Jiong <djduanjiong@gmail.com>

### CODE REVIEW

**Comment by duanjiong** [comment]
#101

**Comment by zheng1** [comment]
It is more convenient to support the definition of count in the annotation, and we also need to support the modification operation. But now this modification is a big improvement

**Pull request merged**
